[package]
name = "vane-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
vane = { path = "../vane" }
elf = "0.8.0"
clap = { version = "4", features = ["derive"] }

[profile.release]
opt-level = "s"
